
services:


  database:
    image: postgres
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=khalil
    condition: service_started
    restart: always

  backend:
    build: ../backend
    restart: always

    
  frontend:
    build: ../frontend
    depends_on:
      - backend

    restart: always

  nginx:
    image: nginx

    depends_on:
      - frontend
      - backend
    restart: always

networks:
  default:
    driver: host




    

