
services:
  nginx:
    image: nginx

    depends_on:
      - frontend
    restart: always


  frontend:
    build: ../frontend

    depends_on:
      - backend

    restart: always

  backend:
    build: ../backend

    depends_on:
      - database
    restart: always


  database:
    image: postgres

    environment:
      - POSTGRES_PASSWORD=khalil
      - POSTGRES_USER=khalil
      - POSTGRES_DB=khail

    restart: always
    


networks:
  default:
    driver: host
