
services:


  database:
    image: postgres
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=khalil
    restart: always

  backend:
    build: ../backend
    depends_on:
      database:
        condition: service_started
        
    restart: always

    
  frontend:
    build: ../frontend
    depends_on:
      - backend
      - database

    restart: always

  nginx:
    build: .
    depends_on:
      - frontend
      - backend
      - database

    restart: always

networks:
  default:
    driver: host




    

