services:
  database:
    image: postgres
    shm_size: 128mb
    network_mode: host
    environment:
      - POSTGRES_PASSWORD=khalil
    restart: always

  backend:
    build: ../backend
    network_mode: host
    depends_on:
      - database
    restart: always

  frontend:
    build: ../frontend
    network_mode: host
    depends_on:
      - database
      - backend

    restart: always

  nginx:
    build: .
    network_mode: host
      - frontend
      - backend
      - database

    restart: always
