
services:

  database:
    image: postgres
    network_mode: "host"
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=khalil
    condition: service_completed_successfully
    restart: always


  backend:
    build: ../backend
    network_mode: "host"
    depends_on:
      - database


    restart: always

    
  frontend:
    build: ../frontend
    network_mode: "host"
    depends_on:
      - backend

    restart: always

  nginx:
    image: nginx
    network_mode: "host"
    depends_on:
      - frontend
      - backend
    restart: always







    

