
services:


  database:
    image: postgres
    shm_size: 128mb
    network_mode: host
    environment:
      - POSTGRES_PASSWORD=khalil
    restart: always

  backend:
    build: ../backend
    network_mode: host
    depends_on:
      database:
        condition: service_started
    restart: always

    
  frontend:
    build: ../frontend
    network_mode: host
    depends_on:
      database:
        condition: service_started
      backend:
        condition: service_started


    restart: always

  nginx:
    build: .
    network_mode: host
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_started
      database:
        condition: service_started

    restart: always






    

