
  backend:
    build: ../backend
    network_mode: "host"
    restart: always

    
  frontend:
    build: ../frontend
    network_mode: "host"
    depends_on:
      - backend

    restart: always

  nginx:
    image: nginx
    network_mode: "host"
    depends_on:
      - frontend
      - backend
    restart: always







    

