services:
  database:
    image: postgres
    network_mode: host
    environment:
      - POSTGRES_PASSWORD=khalil
    restart: always



  frontend:
    build: ../frontend
    network_mode: host
    restart: always

  nginx:
    build: .
    network_mode: host
    restart: always

