services:
  database:
    image: postgres
    network_mode: host
    environment:
      - POSTGRES_PASSWORD=khalil
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: always

  backend:
    build: ../backend
    network_mode: host
    restart: always
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build: ../frontend
    network_mode: host
    restart: always
    depends_on:
      - database
      - backend

  
  nginx:
    build: .
    network_mode: host
    restart: always
    depends_on:
      - frontend

