services:
  database:
    build: ../postgres
    network_mode: host
    environment:
      - POSTGRES_PASSWORD=khalil
    restart: always

  backend:
    build: ../backend
    network_mode: host
    restart: always
    depends_on:
      - database

  frontend:
    build: ../frontend
    network_mode: host
    restart: always
    depends_on:
      - database
      - backend

  
  nginx:
    build: .
    network_mode: host
    restart: always
    depends_on:
      - frontend

